apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: bus-arrivals
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: mrt-crowd
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: carpark-lots
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: ev-stations
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: taxi-positions
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 2
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1
kind: KafkaTopic
metadata:
  name: train-alerts
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka
spec:
  partitions: 1
  replicas: 1