apiVersion: sparkoperator.k8s.io/v1beta2
kind: SparkApplication
metadata:
  name: transit-streaming
  namespace: spark-operator
spec:
  type: Python
  pythonVersion: "3"
  mode: cluster
  image: "apache/spark-py:3.5.0"
  mainApplicationFile: "s3a://sg-transit-data/jobs/streaming_job.py"
  sparkVersion: "3.5.0"
  restartPolicy:
    type: Always
    onFailureRetries: 3
    onFailureRetryInterval: 30
  deps:
    packages:
      - "org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.0"
      - "org.mongodb.spark:mongo-spark-connector_2.12:10.2.0"
      - "org.apache.hadoop:hadoop-aws:3.3.4"
      - "com.amazonaws:aws-java-sdk-bundle:1.12.262"
  driver:
    cores: 1
    memory: "1g"
    serviceAccount: spark
    env:
    - name: KAFKA_BOOTSTRAP
      valueFrom:
        configMapKeyRef:
          name: transit-config
          key: KAFKA_BOOTSTRAP
    - name: MONGODB_URI
      valueFrom:
        secretKeyRef:
          name: transit-secrets
          key: MONGODB_URI
    - name: MINIO_ENDPOINT
      valueFrom:
        configMapKeyRef:
          name: transit-config
          key: MINIO_ENDPOINT
    - name: MINIO_BUCKET
      valueFrom:
        configMapKeyRef:
          name: transit-config
          key: MINIO_BUCKET
    - name: MINIO_ACCESS_KEY
      valueFrom:
        secretKeyRef:
          name: transit-secrets
          key: MINIO_ACCESS_KEY
    - name: MINIO_SECRET_KEY
      valueFrom:
        secretKeyRef:
          name: transit-secrets
          key: MINIO_SECRET_KEY
  executor:
    cores: 1
    instances: 1
    memory: "1g"