apiVersion: v1
kind: ConfigMap
metadata:
  name: transit-config
data:
  KAFKA_BOOTSTRAP: "kafka-kafka-bootstrap.kafka.svc.cluster.local:9092"
  LTA_BASE_URL: "https://datamall2.mytransport.sg/ltaodataservice"
  MINIO_BUCKET: "sg-transit-data"
  MINIO_ENDPOINT: "http://minio.data.svc.cluster.local:9000"
  MONGODB_URI: "mongodb://root:Transit@2024@mongodb.data.svc.cluster.local:27017"
  POLL_BUS_SECONDS: "60"
  POLL_CARPARK_SECONDS: "60"
  POLL_EV_SECONDS: "300"
  POLL_MRT_SECONDS: "600"
  POLL_TAXI_SECONDS: "60"
  REDIS_HOST: "redis-master.data.svc.cluster.local"